- json.go
StandardRegistry.MarshalJSON receiver needs to be a pointer to avoid copy.
> Fix registry race caused by copying a sync.Mutex

- README.md
If you go on the previous URL, it says:
> This is not the Java library.
With a link to the actual Java library, hosted here: https://github.com/dropwizard/metrics
> Metrics URL fixed in the README

- README.md
- librato/librato.go
Tried the new client on one of our services, and it worked just as expected - only the import needed to be changed.
This just starts logging a deprecation notice for anyone importing the client from this repo.
> deprecate librato client + add reference to new home

- registry.go
- registry_test.go
When registered, a metric's name will be prefixed with the prefix
given when creating the registry.
As discussed in #128.
> Add a prefixed registry

- README.md
Hi,
I'd like to suggest adding a link to https://github.com/vrischmann/go-metrics-influxdb in the README.
Since right now there's no available reporter for InfluxDB, I had to make one for work.
Only compatible with InfluxDB 0.9 though.
See also #124.
> add a link to the InfluxDB reporter

- librato/librato.go
Better version of https://github.com/rcrowley/go-metrics/pull/48 that introduces an implementation that doesn't change the api.
> Add stat namespace prefix option for Librato adapter

- README.md
Updates the periodically log example in README.md to pass an explicit `time.Duration` value instead of the value `60e9`.
> make log period more explicit

- .travis.yml
- meter_test.go
- runtime.go
- runtime_gccpufraction.go
- runtime_no_gccpufraction.go
Go 1.5 introduced a new `memstats` variable to get the fraction of the CPU spent by the GC.  This patch adds support for it.
> Add support for fraction of CPU time used by GC

- registry.go
- registry_test.go
`PrefixedRegistry` supports chaining one registry off another, but prior to this commit, the public API did not. `NewPrefixedChildRegistry()` is exactly like `NewPrefixedRegistry()` except it allows an existing `Registry` to be used instead of creating a new registry.
> Add NewPrefixedChildRegistry()

- README.md
- exp/exp.go
not thoroughly tested yet, but seems to work fine so far.
> support serving up go-metrics as expvars

- runtime.go
- runtime_test.go
Add an additional metric for number of native threads used by the process.
> Add native thread count metric

- exp/exp.go
This is meant to resolve issue #166.
A new `ExpHandler` function has been added to the `exp` package. This will return the `http.Handler` currently being used in `Exp()` and will allow users to register the metrics endpoint on a custom path with a router of their choice.
> Adding `exp/ExpHandler` so metrics endpoint can be registered on with other HTTP routers

- README.md
I and aerofile-kite just tried to use this metrics to publish data to ganglia. and succeeded for counter and histogram. I have just added the links so that, people may get help form this and contribute on it to make it more flexible and efficient.
> Ganglia reporter link added.

- exp/exp.go
- registry.go
- registry_test.go
This commit changes the behavior of PrefixedChildRegistry
to only apply the Each function to registered metrics
that have the the appropriate prefix.
This commit contains two changes:
1: An originally failing test showing the behavior
2: A wrapper func around the passed in function
for Each that applies the required filter
The behavior that this addresses was quite unexpected, but happy to discuss if this was the intended behavior.
> ChildRegistry should filter by prefix

- README.md
- gauge.go
- gauge_float64.go
- gauge_float64_test.go
- gauge_test.go
Hi
I would like to add new type of Gauge. Main use case is passing function which returns different values over the time instead of explicit call ``gauge.Updata(newValue)``. It's standard use case in origin Java matrics: 
```java
registry.register(name(SessionStore.class, "cache-evictions"), new Gauge<Integer>() {
@Override
public Integer getValue() {
return cache.getEvictionsCount();
}
});
```
Now I have to implement ``FunctionalGauge`` in all my projects which are using go-metrics, e.g: https://github.com/allegro/marathon-consul/commit/e548d70f7a27be6476550b58e527b67cc9a36e41
Regards
Paweł Szymczyk
> Adding FunctionalGauge

- log.go
Use interface for logger to allow other implementations
see https://github.com/rcrowley/go-metrics/issues/155
> use interface for logger

- README.md
- gauge_test.go
- metrics_test.go
- timer_test.go
My first iteration of a metrics client had code like this:
```go
// Increment a counter with the given name.
func Increment(name string) {
mn := getWithNamespace(name)
m := metrics.GetOrRegister(mn, metrics.NewMeter()).(metrics.Meter)
m.Mark(1)
}
```
Which contained a massive resource leak - every anonymous NewMeter() call
appends a new arbiter, so I had one arbiter for each function call! Instead
document the right way to do this so people hopefully don't get as lost.
Initially opened as #165, but I no longer have permission to push to the origin
used for that PR. The only change is I fixed the conflict (two branches added
tests at the bottom of the same file)
> Document how to create a threadsafe registry

- gauge.go
- gauge_float64_test.go
- registry.go
- registry_test.go
Hello.
We have a gofmt check in out git pre-commit hook which prevents a commit if it contains code with formatting issues. We vendor go-metrics, and since it has the formatting issues we have to sidestep the pre-commit hook check. Would you please so kind to merge the formatting changes?
Thank you.
> gofmt the code

- sample.go
This should enable folks to create alternative `Sample` implementations outside the `go-metrics` package namespace.
Addresses #188
> [fixes #188] expose a constructor for SampleSnapshot

- README.md
- meter.go
- meter_test.go
- registry.go
- registry_test.go
- timer.go
- timer_test.go
based on https://github.com/rcrowley/go-metrics/pull/197
- added `Stop` to timer.
- call `Stop` when metrics are unregistered.
- use lock in `meter Stop()` to avoid data races accessing the `stopped` flag.
- when called `meter Mark()`, return if meter is already stopped (without panicking).
> Stop timer/meter

- meter.go
- meter_test.go
this also removes the meter from the tickers.
> add Stop() to Meter

- json.go
- registry.go
This method will allow the library user to export the metrics as yaml or any other format.
> Add dump method for standard registry

- README.md
Would kindly like to add the Wavefront client to the README.
Wavefront (a SaaS based monitoring solution owned by VMware) has a `go-metrics-wavefront` client that is used widely.
> Added Wavefront Client to README

- meter.go
- meter_test.go
> Replace lock with CAS in standard meter stop

- README.md
I published a client for the newer AppOptics tagged metrics API (based off @mihasya 's original Librato source-based client - which is great!). Just adding a link to it.
> Add appoptics client link to README
